development:
  email_user_name: <%= ENV['email_user_name'] %>
  email_password: <%= ENV['email_password'] %>

production:
  email_user_name: ENV["email_user_name"]
  email_password: ENV["email_password"]